{
  "uid" : "792858930f38457c",
  "name" : "test_1_1_get_exact_comments_from_post_13_",
  "fullName" : "TestCases.Test_For10Clouds#test_1_1_get_exact_comments_from_post_13_",
  "historyId" : "6d21bf052a5537c0aae19a26848443c6",
  "time" : {
    "start" : 1578779381344,
    "stop" : 1578779381516,
    "duration" : 172
  },
  "status" : "broken",
  "statusMessage" : "NameError: name 'assert_that' is not defined",
  "statusTrace" : "precondition = None\n\n    @pytest.mark.GET\n    def test_1_1_get_exact_comments_from_post_13_(precondition):\n        # API_URL\n        url = 'https://jsonplaceholder.typicode.com/posts/13/comments/'\n        payload = {'postId': 13, 'id': 61}\n        response = requests.get(url, params=payload)\n        print(response.text)\n        response_code = response.status_code\n        print(response_code)\n        assert response_code == 200\n>       assert_that(response.ok, 'HTTP Request OK').is_true()\nE       NameError: name 'assert_that' is not defined\n\nTest_For10Clouds.py:47: NameError",
  "flaky" : false,
  "beforeStages" : [ {
    "name" : "precondition",
    "time" : {
      "start" : 1578779381071,
      "stop" : 1578779381071,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "NameError: name 'assert_that' is not defined",
    "statusTrace" : "precondition = None\n\n    @pytest.mark.GET\n    def test_1_1_get_exact_comments_from_post_13_(precondition):\n        # API_URL\n        url = 'https://jsonplaceholder.typicode.com/posts/13/comments/'\n        payload = {'postId': 13, 'id': 61}\n        response = requests.get(url, params=payload)\n        print(response.text)\n        response_code = response.status_code\n        print(response_code)\n        assert response_code == 200\n>       assert_that(response.ok, 'HTTP Request OK').is_true()\nE       NameError: name 'assert_that' is not defined\n\nTest_For10Clouds.py:47: NameError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "eef6386dac5bcfe1",
      "name" : "stdout",
      "source" : "eef6386dac5bcfe1.txt",
      "type" : "text/plain",
      "size" : 336
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "tag",
    "value" : "GET"
  }, {
    "name" : "parentSuite",
    "value" : "TestCases"
  }, {
    "name" : "suite",
    "value" : "Test_For10Clouds"
  }, {
    "name" : "host",
    "value" : "HataRide"
  }, {
    "name" : "thread",
    "value" : "5656-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "TestCases.Test_For10Clouds"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "GET" ]
  },
  "source" : "792858930f38457c.json",
  "parameterValues" : [ ]
}